# Generated by Django 6.0.3 on 2026-03-26 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_auth_user_id;"
            "ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_custom_user_id "
            "FOREIGN KEY (user_id) REFERENCES custom_user(id) ON DELETE CASCADE;",
            reverse_sql="ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_custom_user_id;"
            "ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id "
            "FOREIGN KEY (user_id) REFERENCES auth_user(id) ON DELETE CASCADE;"
        ),
    ]
