name: CI - RetailShopAPI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: retailshop-backend:ci
  deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Start SSH agent and add key
          uses: webfactory/ssh-agent@v0.9.0
          with:
            ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
  
        - name: Add EC2 host to known_hosts
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
  
        - name: Deploy on EC2
          run: |
            ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << "EOF"
              set -e
              cd /home/ubuntu/
              sudo rm -rf RetailShopAPI
              git clone https://github.com/MyoThuraLwin/RetailShopAPI
              cd RetailShopAPI
              cp /home/ubuntu/myproject.env /home/ubuntu/RetailShopAPI/.env
              docker build -t postgres_db:latest .
              docker rm -f postgres_db || true
              docker run -d                   --name postgres_db                   --network app_net                    -p 8000:8000                   django_app:latest
              docker exec postgres_db python manage.py migrate
            EOF
