# Generated by Django 6.0.3 on 2026-03-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_remaining_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(help_text='Product Code', max_length=50, unique=True),
        ),
    ]
